### ISSUE TITLE
Selecting same standard twice removes "Standardized Date/Place" indicator

### ISSUE THREAD

**Issue by Norman-Amy** [FamilySearchElements/birch-standards-picker#39]
I attempted to fix the indicator disappearing by removing the check for if the data hadn't changed in `_updateData()`, but then sometimes even if I selected a different one, the indicator wouldn't appear. I'm not sure how would be best to fix this.

**Comment by jpodwys** [comment]
I'm not sure I understand how to reproduce this. I just used the standards picker we have in the Gallery to select the same standardized place twice and it shows the indicator. Can you please tell me more about your use case?

**Comment by Norman-Amy** [comment]
It's very inconsistent, so I'm not sure what's causing it, but maybe this will help:
![d2gvqu5t6z](https://user-images.githubusercontent.com/10411450/26938901-dc21270a-4c32-11e7-98ec-ed4987b81853.gif)

**Comment by jpodwys** [comment]
Wow, that's odd. I haven't seen that behavior before. Thank you for the detailed demo.

I was able to reproduce it. Here are the steps:

1. Type something
2. Select a standard from the typeahead
3. Delete a character or two (the typeahead will show up again)
4. Select the same exact standard from the typeahead as before

I'll look into this.

**Comment by jpodwys** [comment]
I just pushed up the `standard-indicator-fix` branch. I tested it locally and it appears to be working well. Please pin to it and let me know if it fixes the issue for you.

**Comment by Norman-Amy** [comment]
I tested it out and it works great! Thanks for taking the time to fix it.

**Comment by jpodwys** [comment]
Released as `2.5.1`.
