### ISSUE TITLE
Side-by-side date & place standards picker: when a standard is returned, standards-picker field steals focus

### ISSUE THREAD

**Issue by skye2k2** [FamilySearchElements/birch-standards-picker#44]
Observed behavior: on a throttled connection, quickly entering a date, tabbing out, and quickly typing additional data, when the standard is returned, focus is placed back on that field, and the remainder of the user's entered text ends up in the previous field. A little weird.

**Comment by jpodwys** [comment]
@straker and I discussed this last week and he said he would try to put a PR together.

**Comment by jpodwys** [comment]
I believe the has been addressed. Can you confirm?

**Comment by skye2k2** [comment]
This issue appears to be resolved. :thx:
